### ISSUE TITLE
Adding all data used in WP4 for the spatial analysis in Copenhagen - 11 data sets

### ISSUE THREAD

**Issue by camilimaz** [emotional-cities/data-share#1]
# Partner
DTU

# S3 Folder
s3://emotional-cities/data/dtu/WP4 Spatial Analysis/
11 data sets

# Checklist
- [x] Data uploaded to S3.
- [x] Metadata records created (one per each dataset).

**Comment by PascalLike** [comment]
For the records:

```
Air_pollution_wZones.csv
dst_2012_wZones.csv
dst_2013_wZones.csv
dst_2014_wZones.csv
dst_2015_wZones.csv
dst_2016_wZones.csv
dst_2017_wZones.csv
dst_2018_wZones.csv
landuse_POI_wZones.csv
noise_wZones.csv
zones.csv
```

**Comment by PascalLike** [comment]
https://emotional.byteroad.net/collections/air_pollution_wzones
https://emotional.byteroad.net/collections/dst_2012_wzones
https://emotional.byteroad.net/collections/dst_2013_wzones
https://emotional.byteroad.net/collections/dst_2014_wzones
https://emotional.byteroad.net/collections/dst_2015_wzones
https://emotional.byteroad.net/collections/dst_2016_wzones
https://emotional.byteroad.net/collections/dst_2017_wzones
https://emotional.byteroad.net/collections/dst_2018_wzones
https://emotional.byteroad.net/collections/landuse_poi_wzones
https://emotional.byteroad.net/collections/zones
https://emotional.byteroad.net/collections/noise_wzones

And metadata:

https://emotional.byteroad.net/collections/ec_catalog/items/air_pollution_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2012_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2013_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2014_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2015_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2016_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2017_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/dst_2018_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/landuse_poi_wzones
https://emotional.byteroad.net/collections/ec_catalog/items/zones
https://emotional.byteroad.net/collections/ec_catalog/items/noise_wzones
