### ISSUE TITLE
Update of all datasets used in the WP4 hotspots report for Lisbon (IGOT) (except 'Vibrancy index', which is a new one) to incorporate graphic scale

### ISSUE THREAD

**Issue by joaopmreis** [emotional-cities/data-share#2]
# Partner
IGOT

# S3 Folder
s3://emotional-cities/data/igot/wp4_hotspots_report_data/
37 datasets (except **s3://emotional-cities/data/igot/wp4_hotspots_report_data/lisbon_vibrancy_index.gpkg**)

# Checklist
- [x] Updated data uploaded to S3.
- [ ] Outdated data deleted from S3. (deletion of .geojson and .sld files from **s3://emotional-cities/data/igot/** folder)
- [x] Metadata record updated.

**Comment by PascalLike** [comment]
The 37 datasets have been reloaded with the associated style.
