### ISSUE TITLE
Adding 'Vibrancy index' dataset used in the WP4 hotspots report for Lisbon (IGOT)

### ISSUE THREAD

**Issue by joaopmreis** [emotional-cities/data-share#3]
# Partner
IGOT

# S3 Folder
s3://emotional-cities/data/igot/wp4_hotspots_report_data/
1 dataset (**s3://emotional-cities/data/igot/wp4_hotspots_report_data/lisbon_vibrancy_index.gpkg**)

# Checklist
- [x] Data uploaded to S3.
- [x] Metadata records created (one per each dataset).

**Comment by PascalLike** [comment]
The dataset has been reloaded with the associated style.

https://emotional.byteroad.net/collections/ec_catalog/items/lisbon_vibrancy_index
